# Generated by Django 5.1.15 on 2026-09-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('student_email', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('teacher_department', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('time_slot', models.CharField(blank=True, max_length=100, null=True)),
                ('agenda', models.CharField(blank=True, max_length=500, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('requested_at', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_at', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
