# Generated by Django 5.1.15 on 2026-09-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrelloBoard',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('background', models.CharField(blank=True, max_length=255, null=True)),
                ('creator_email', models.CharField(blank=True, max_length=255, null=True)),
                ('starred', models.BooleanField(default=False)),
                ('members', models.JSONField(blank=True, default=list)),
                ('join_requests', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TrelloCard',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('column_id', models.CharField(db_index=True, max_length=100)),
                ('board_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.CharField(blank=True, max_length=100, null=True)),
                ('sequence', models.IntegerField(default=0)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrelloColumn',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('board_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
    ]
