# Generated by Django 5.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="color",
            field=models.CharField(default="#264796", max_length=20),
        ),
        migrations.AddField(
            model_name="classroom",
            name="course_plan_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="classroom",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
