# Generated by Django 5.1.15 on 2026-09-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(default='custom', max_length=50)),
                ('color', models.CharField(default='#264796', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('recurrence', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=255, null=True)),
                ('student_email', models.CharField(blank=True, max_length=255, null=True)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_calendar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['start_time', '-id'],
            },
        ),
    ]
