# Generated by Django 5.1.15 on 2026-09-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChainAnswerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('teacher_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(default='New Game', max_length=255)),
                ('chain_variation', models.CharField(default='standard', max_length=50)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty_level', models.CharField(default='medium', max_length=50)),
                ('language', models.CharField(default='en', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='setup', max_length=50)),
                ('starting_word', models.CharField(default='Apple', max_length=100)),
                ('time_per_turn', models.IntegerField(default=30)),
                ('max_words', models.IntegerField(blank=True, null=True)),
                ('ai_suggestions', models.TextField(blank=True, null=True)),
                ('penalty_on_invalid', models.BooleanField(default=False)),
                ('penalty_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('join_order', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('words_submitted', models.IntegerField(default=0)),
                ('words_valid', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.chainanswergame')),
            ],
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='games.chainanswergame')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('submitted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('validation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='games.chainanswergame')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
