# Generated by Django 5.1.15 on 2026-09-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(default='ready', max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('template_path', models.CharField(blank=True, max_length=500, null=True)),
                ('docx_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
