# Generated by Django 5.1.15 on 2026-09-08 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0003_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('syllabus_context', models.TextField(blank=True, null=True)),
                ('lecture_flow', models.TextField(blank=True, null=True)),
                ('examples', models.TextField(blank=True, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('quiz_questions', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(default=0)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='classrooms.classroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
